// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phuqoagoadmgpilcwwom.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBodXFvYWdvYWRtZ3BpbGN3d29tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1ODg3MDIsImV4cCI6MjA2NzE2NDcwMn0.yaM4T3MOlGTm7Mo9wm-5AmCwDwLmZvw63hPUI8C3QL4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});